[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[project]
name = 'rounders'
version = "0.3.0"
description = 'round-function equivalents with different rounding-modes'
readme = 'README.md'
requires-python = '>=3.10'
authors = [{ name = 'Mark Dickinson', email = 'dickinsm@gmail.com' }]
keywords = [
    'round',
    'rounding',
    'significant figures',
    'decimal places',
    'rounding mode',
]
classifiers = [
    'License :: OSI Approved :: Apache Software License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Topic :: Scientific/Engineering :: Mathematics',
]

[project.urls]
source = 'https://github.com/mdickinson/rounders'

[dependency-groups]
dev = [
    "coverage>=7.6.1",
    "mypy>=1.14.1",
    "pytest>=8.3.5",
]

[tool.coverage.run]
branch = true
source_pkgs = ["rounders"]
command_line = "-m pytest"

[tool.mypy]
packages = ["rounders"]
strict = true

[tool.pytest.ini_options]
addopts = ["--pyargs", "--import-mode=importlib"]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
extend-select = ["D", "I", "UP", "W"]  # pydocstyle, isort, pyupgrade, pycodestyle warns

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["D102"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
