# Run style checks

name: style

on:
  - pull_request
  - workflow_dispatch

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: python -m pip install ruff
      - name: Run style checks
        run: |
          python -m ruff format --check --diff
          python -m ruff check
